package com.kantek.dancer.booking.domain.model.response

import com.kantek.dancer.booking.domain.model.response.lawyer.LawyerDTO

data class BookingDTO(
    val address: String,
    val country_id: Any,
    val created_at: String,
    val customer_email: Any,
    val customer_first_name: Any,
    val customer_last_name: Any,
    val customer_name: Any,
    val customer_phone: Any,
    val datetime_utc: Any,
    val description: String,
    val district_id: Any,
    val end_date: Any,
    val end_time: Any,
    val gender: Any,
    val id: Int,
    val is_vip: Boolean,
    val language_skill: Any,
    val languages: List<LanguageDTO>,
    val meta_data: Any,
    val note: Any,
    val partner_id: Any,
    val payment_method: Any,
    val payment_token: Any,
    val payment_type: Any,
    val price: Any,
    val province_id: Any,
    val quantity: Int,
    val reason_cancel: String,
    val reason_partner_cancel: Any,
    val services: List<Any>,
    val start_date: Any,
    val start_time: Any,
    val status: Int,
    val status_payment: Int,
    val status_title: String,
    val status_title_for_partner: String,
    val timezone: Any,
    val total_payment: Any,
    val type_price: String,
    val type_service_id: Any,
    val updated_at: String,
    val partner_account: LawyerDTO?,
    val user: UserDTO?,
    val user_id: Int,
    val type_service: List<SpecialityDTO>?,
    val is_review: Boolean = false
)